### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by gabriellimma** [eugustavo/github-badges#8]
Na parte:
```
# Acesse o repositório
$ cd eugustavo/github-badges
```
não serua melhor colocar apenas:
`$ cd github-badges`
pois o repositório, neste caso, quando clonado não leva o nome do criador.

**Comment by eugustavo** [comment]
Opa Gabriel, tudo na paz?

Realmente, atualizei o README! Muito obrigado pela observação. 💚
